# Generated by Django 5.0.4 on 2024-05-20 16:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Salad', 'Salad'), ('Snack', 'Snack'), ('Drink', 'Drink'), ('Soup', 'Soup'), ('Vegeterian', 'Vegeterian')], max_length=50)),
                ('description', models.TextField()),
                ('process', models.TextField()),
                ('ingredients', models.TextField()),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('recipe_type', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Salad', 'Salad'), ('Snack', 'Snack'), ('Drink', 'Drink'), ('Soup', 'Soup'), ('Vegeterian', 'Vegeterian')], max_length=20)),
            ],
        ),
    ]
