# Generated by Django 5.0.4 on 2024-05-21 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_alter_recipe_category_alter_recipe_recipe_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Salad', 'Salad'), ('Snack', 'Snack'), ('Drink', 'Drink'), ('Soup', 'Soup'), ('Chicken', 'Chicken'), ('Vegetarian', 'Vegetarian')], max_length=50),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_type',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Salad', 'Salad'), ('Snack', 'Snack'), ('Drink', 'Drink'), ('Soup', 'Soup'), ('Chicken', 'Chicken'), ('Vegetarian', 'Vegetarian')], max_length=20),
        ),
    ]
